# Generated by Django 5.0.3 on 2024-04-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lower Bound')),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Upper Bound')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents_photos/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP/Postal Code')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visible')),
                ('bedroom_count', models.IntegerField(verbose_name='Bedrooms')),
                ('bathroom_count', models.IntegerField(verbose_name='Bathrooms')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='listing_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='listing_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='listing_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='listing_photos/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.agent', verbose_name='Agent')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.neighborhood', verbose_name='Neighborhood')),
                ('price_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pricerange', verbose_name='Price Range')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.propertytype', verbose_name='Property Type')),
                ('sale_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.salestatus', verbose_name='Sale Status')),
            ],
        ),
    ]
